parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.6.2'
        charset: utf8
        host:     "ec2-54-217-245-66.eu-west-1.compute.amazonaws.com"
        port:     5432
        dbname:   "d341epfm8mg05a"
        user:     "xhaafvnjosfuma"
        password: "249908cfabdfb3cb04dce5cff53e6876f3d27171e9507015ddbc82931615ab0d"

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
