parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.6.2'
        charset: utf8
        host:     "ec2-107-20-188-239.compute-1.amazonaws.com"
        port:     5432
        dbname:   "d9gpe0uhqe9t92"
        user:     "dknbqcuhkzcmlw"
        password: "d7b10a95cc6d3726ffac99bdf55c18eef4b95821a69af8bae9f55c4eea746875"

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
