# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  logger_startup_message: 'Logger just got started!!! (from original config)'
  api:
    uri: https://api.irail.be
  twitter:
    consumer_key: '%env(TWITTER_CONSUMER_KEY)%'
    consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
    access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    access_token_secret: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'
  telegram:
    bot_api_key: '%env(TELEGRAM_BOT_API_KEY)%'
    bot_username: '%env(TELEGRAM_BOT_USERNAME)%'
    public_channel: '%env(TELEGRAM_PUBLIC_CHANNEL)%'
  locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    drupol\sncbdelay\:
        resource: '../src/*'
        exclude: '../src/{Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    drupol\sncbdelay\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    sncbdelay.httpclient:
        public: true
        class: Symfony\Component\HttpClient\NativeHttpClient
        #arguments: [[], '10']

    sncbdelay.departures:
        class: drupol\sncbdelay\Strategies\IRail\Storage\Departures

    sncbdelay.strategy:
        class: drupol\sncbdelay\Strategies\IRail\IRail
        public: true
        arguments: ['@parameter_bag', '@event_dispatcher', '@logger', '@sncbdelay.httpclient', '@sncbdelay.departures']

    drupol\sncbdelay\EventSubscriber\Debug\Alert:
        arguments: ['@parameter_bag', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']
    drupol\sncbdelay\EventSubscriber\Debug\Canceled:
        arguments: ['@parameter_bag', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']
    drupol\sncbdelay\EventSubscriber\Debug\Custom:
        arguments: ['@parameter_bag', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']
    drupol\sncbdelay\EventSubscriber\Debug\Delay:
        arguments: ['@parameter_bag', '@twig', '@logger', '@cache.app', '@doctrine.orm.entity_manager']
